### ISSUE TITLE
Can it be converted into an onnx model for easy deployment?

### ISSUE THREAD

**Issue by wyd520520** [google-research/omniglue#10]
Can it be converted into an onnx model for easy deployment?

**Comment by arjunkarpur** [comment]
Actually @Vincentqyw has just done this already :)

https://github.com/Vincentqyw/omniglue-onnx

https://x.com/AlphaRealcat/status/1794077805422223676

**Comment by arjunkarpur** [comment]
Resolving - please re-open if this didn't answer your question.
